spring.application.name=snixtennis
server.port=1000
spring.datasource.url=jdbc:mysql://localhost:3306/snix?zeroDateTimeBehavior=CONVERT_TO_NULL
spring.datasource.username=root
spring.datasource.password=supergamo123.
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.application.name=app_assisants
spring.thymeleaf.cache=false
spring.thymeleaf.enabled=true
spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html
logging.level.org.hibernate=DEBUG
multipart.enabled=true
spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation=true
debug= true
spring.servlet.multipart.max-file-size=20MB
spring.servlet.multipart.max-request-size=30MB
valor.ruta=C:\\Users\\sauma\\Documents\\NetBeansProjects\\asistantProject\\src\\main\\resources\\static\\
valor.form=C:\\Users\\sauma\\Documents\\NetBeansProjects\\asistantProject\\src\\main\\resources\\templates\\formularios\\
spring.profile.active=local