
server.port=1000
spring.datasource.url=jdbc:mysql://localhost:3306/snix?zeroDateTimeBehavior=CONVERT_TO_NULL
spring.datasource.username=root
spring.datasource.password=supergamo123.
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.application.name=snixTennis
spring.thymeleaf.cache=false
spring.thymeleaf.enabled=true
spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html
logging.level.org.hibernate=DEBUG
server.servlet.session.cookie.same-site=none
server.servlet.session.cookie.secure=true
cors.allowed.origins= http://localhost:5500, http://127.0.0.1:5500
Access-Control-Allow-Origin: http://localhost:5500,  http://127.0.0.1:5500
Access-Control-Allow-Credentials: true
Vary: Origin

spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation=true
debug= true
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB
spring.servlet.multipart.enabled=true
valor.ruta=C:\\Users\\sauma\\Documents\\Snix\\images\\
valor.form=C:\\Users\\sauma\\Documents\\snixtennis\\src\\main\\resources\\templates\\formularios\\
spring.profile.active=local

